### ISSUE TITLE
PVC with annotation of volume.beta.kubernetes.io/storage-class fails to create volumesnapshot

### ISSUE THREAD

**Issue by netzzer** [konveyor/oadp-operator#54]
If a PVC only has the storageclass defined via an annotation the velero-csi plugin does not create a volumesnapshot for the PVC when a backup is triggered. Need to have snapshot triggered for both ways of specifying storageclass for a PVC.

Annotation for specifying storage-class. Does NOT currently work with velero-csi plugin:
```
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-class: ocs-storagecluster-cephfs
      volume.beta.kubernetes.io/storage-provisioner: openshift-storage.cephfs.csi.ceph.com
```
In the PVC spec. This works correctly with velero-csi plugin:
```
  spec:
    accessModes:
    - ReadWriteMany
    dataSource:
      apiGroup: snapshot.storage.k8s.io
      kind: VolumeSnapshot
      name: velero-my-shared-storage-zw2pg
    resources:
      requests:
        storage: 1Gi
    storageClassName: ocs-storagecluster-cephfs
    volumeMode: Filesystem
```
