### ISSUE TITLE
Problems with region endpoint URL

### ISSUE THREAD

**Issue by hmuchaku** [konveyor/oadp-operator#80]
We use oadp-oeprator with ROKS (managed Openshift on IBMCloud).
We failed to set-up oadp-operator with ICOS(S3 compatible IBM Cloud Object Storage)endpoint due to the following error,
- panic: invalid region provided: jp-tok

This is because jp-tok is an IBM region name that AWS does not have.
I know that  we can bypass region check with env "REGISTRY_STORAGE_S3_REGIONENDPOINT",
but the value of s3url has been ignored.
veloro setup YAML:
```
apiVersion: konveyor.openshift.io/v1alpha1
kind: Velero
metadata:
  name: velero
  namespace: oadp-operator
spec:
  olm_managed: true
  backup_storage_locations:
  - config: 
      region: us-east-1
      s3ForcePathStyle: true
      s3Url: 'https://s3.private.jp-tok.cloud-object-storage.appdomain.cloud'
...
```
oadp-default-aws-registry env:
```
...
          env:
            - name: REGISTRY_STORAGE
              value: s3
            - name: REGISTRY_STORAGE_S3_ACCESSKEY
              value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - name: REGISTRY_STORAGE_S3_BUCKET
              value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            - name: REGISTRY_STORAGE_S3_REGION
              value: jp-tok
            - name: REGISTRY_STORAGE_S3_SECRETKEY
              value: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
...
```
We can work around this by manually adding env REGISTRY_STORAGE_S3_REGIONENDPOINT to oadp-default-aws-registry  deployment, but I don't think this is recommended since this deployment controlled by an operator.
How should I handle this?

**Comment by GMerigo** [comment]
I have the same problem with regular AWS region eu-south-1 (Milan), the aws registry exits with invalid region.

```
oc logs -f pod/oadp-default-aws-registry-668bc8d44c-kds6f -n oadp-operator 
time="2021-03-29T07:32:08.461219176Z" level=info msg="debug server listening :5001"
panic: invalid region provided: eu-south-1
```

Is there a way to bypass the error or is there a new image we could use to include valid aws regions?

**Comment by sseago** [comment]
@GMerigo So from the issue as reported, it looks like we need to add an optional `REGISTRY_STORAGE_S3_REGIONENDPOINT` environment variable to the registry deployment definition. I'm wondering whether an issue with unrecognized AWS-hosted regions is actually an unrelated problem. It may be that for that, the real issue is we need a newer version of the docker registry image that recognizes this region name.

**Comment by GMerigo** [comment]
@sseago I did just that, I was wondering if  the operator would remove the variable when it reconciles the registry.

**Comment by sseago** [comment]
@GMerigo So I just started looking at the code this morning. It looks like that env var should be set based on `s3URL` -- but perhaps there's a bug and something isn't coming across properly. Might just be a typo somewhere else in the templates. I'll have to try it out a bit later to see what happens in my environment
```
{% if bsl.config.s_3__url is defined %}
          - name: REGISTRY_STORAGE_S3_REGIONENDPOINT
            value: {{ bsl.config.s_3__url }}
```
https://github.com/konveyor/oadp-operator/blob/master/roles/velero/templates/registry_aws.yml.j2#L37-L39

**Comment by sseago** [comment]
@GMerigo So in the OADP Velero CR, the BSL configuration parameters must be written in snake_case rather than camelCase. Taking your above example, the two s3 params should be changes as follows:
```
apiVersion: konveyor.openshift.io/v1alpha1
kind: Velero
metadata:
  name: velero
  namespace: oadp-operator
spec:
  olm_managed: true
  backup_storage_locations:
  - config: 
      region: us-east-1
      s3_force_path_style: true
      s3_url: 'https://s3.private.jp-tok.cloud-object-storage.appdomain.cloud'
...
```
To resolve this issue,  I will add a note to the doc at https://github.com/konveyor/oadp-operator/blob/master/docs/bsl_and_vsl.md to indicate that this is necessary.
