### ISSUE TITLE
Are volume snapshot backups supposed to be moved to s3?

### ISSUE THREAD

**Issue by GMerigo** [konveyor/oadp-operator#86]
I've set up oadp by the book, currently I'm testing on OCP4.6 on AWS, using gp2-csi volumes.
I tried manually and the snapshots are ok.

Here is the yaml file (I uploaded in .txt otherwise Github doesn't let me upload it)

[konveyor.openshift.io_v1alpha1_velero_cr.yaml.txt](https://github.com/konveyor/oadp-operator/files/6227339/konveyor.openshift.io_v1alpha1_velero_cr.yaml.txt)

I'm looking into the s3 and I don't see any snapshot content (I expect the snapshot content for a new volume to be around 200MB as it contains a default mysql persistent volume witch get initialized from an empty one).

My backup is as follows:

```yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  namespace: oadp-operator
  name: backuptestdb
spec: 
  includedNamespaces:
    - backuptest
  storageLocation: default
  defaultVolumesToRestic: false
  ttl: 720h0m0s
```

Note that the restore works, but in my opinion only because the volumesnapshotclass is set to Retain, so the snapshot is retained on the volume storage even after I delete the backuptest project and it's restored from there. I set the class to Retain because of a velero warning that told me so.

Is there any way to move the volume backup to s3 and having the volumesnapshot class set to Delete so the restore happens directly from “offline” media such as the s3 bucket and not from the snapshot? I'm feeling I'm missing some important information.

I would rather not use restic as it has high resource requirements when volumes get large since we can leverage EBS snapshots.
