### ISSUE TITLE
annotation not present in restore

### ISSUE THREAD

**Issue by gudroot** [konveyor/oadp-operator#90]
hi, i installed oadp-operator in OKD 4.7

i configured a velero cr like this:

```
spec:
  backup_storage_locations:
  - config:
      insecure_skip_tls_verify: true
      profile: default
      region: aws
      s3_force_path_style: true
      s3_url: http://minio-velero-hl.minio-velero.svc.cluster.local:9000
    credentials_secret_ref:
      name: cloud-credentials
      namespace: oadp-operator
    name: default
    object_storage:
      bucket: origin-backup
      prefix: velero
    provider: aws
  default_velero_plugins:
  - aws
  - openshift
  enable_restic: true
  olm_managed: true
```

the schedule is created as follows:
```
  spec:
    schedule: 56 11 * * *
    template:
      defaultVolumesToRestic: true
      includedNamespaces:
      - default
      - testns
      ttl: 720h0m0s
```

a backup is created that contains the pods in namespace 'testns'. that pod contains the annotation 
```
    openshift.io/scc: anyuid
```

as far as i can tell the annotation is present in the backup.

when i delete the pod and restore it from the backup created by the schedule the scc is set to

```
    openshift.io/scc: restricted
```

is this intended? i would have expected the annotation to be the same in the original pod and the restored pod.
